namespace MyAmazingConsole.Models;

/// <summary>
/// Represents a customer order containing one or more line items.
/// Each order is automatically assigned a unique identifier and a creation timestamp.
/// The <see cref="TotalCost"/> is computed as the sum of all item totals.
/// </summary>
public class Order
{
    /// <summary>
    /// Gets or sets the unique identifier for this order.
    /// A new <see cref="Guid"/> is generated by default.
    /// </summary>
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Gets or sets the customer who placed this order.
    /// </summary>
    public Customer Customer { get; set; } = new();

    /// <summary>
    /// Gets or sets the list of line items included in this order.
    /// </summary>
    public List<OrderItem> Items { get; set; } = [];

    /// <summary>
    /// Gets the total cost of the order, calculated by summing the
    /// <see cref="OrderItem.TotalCost"/> of every item in the <see cref="Items"/> list.
    /// This is a computed property with no backing field.
    /// </summary>
    public decimal TotalCost => Items.Sum(i => i.TotalCost);

    /// <summary>
    /// Gets or sets the current status of the order.
    /// Defaults to <see cref="OrderStatus.Created"/>.
    /// </summary>
    public OrderStatus Status { get; set; } = OrderStatus.Created;

    /// <summary>
    /// Gets or sets the UTC date and time when the order was created.
    /// Defaults to <see cref="DateTime.UtcNow"/> at the time of instantiation.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
